def load_and_process(startup_funding_csv):

    # Method Chain 1 (Load data and drop data)

    df = (
          pd.read_csv("startup_funding_csv.csv")
          .copy().drop(['Remarks','Investors Name', 'Sr No','SubVertical' ], axis=1)
          .rename(columns={"City  Location": "City"})
          .rename(columns={"InvestmentnType": "Investment Type"})
          .dropna(axis=0)
          .replace(',','', regex=True)
          .dropna(axis=0)
           )
    
    df = df[df["City"] != 'San Francisco']
    df = df[df["City"] != 'San Jose']
    df = df[df["City"] != 'Burnsville']
    df = df[df["City"] != 'Menlo Park']
    df = df[df["City"] != 'Palo Alto']
    df = df[df["City"] != 'Santa Monica']
    df = df[df["City"] != 'Singapore']
    df = df[df["City"] != 'New York']
    df = df[df["City"] != 'India/Singapore']
    df = df[df["City"] != 'India/US']
    df = df[df["City"] != 'India']
    df = df[df["City"] != 'California']
    df = df[df["City"] != 'Missourie']
    df = df[df["City"] != 'Boston']
    df = df[df["City"] != 'USA/India']
    df = df[df["City"] != 'New York/ India']
    df = df[df["City"] != 'US/India']
    df = df[df["City"] != 'India / US']
    df = df[df["City"] != 'New York Bengaluru']

    
    df = df.replace("Bengaluru", "Bangalore")
    df = df.replace("Delhi", "New Delhi")
    df = df.replace("Karnataka", "Bangalore")
    df = df.replace("Mumbai/Bengaluru", "Mumbai")
    df = df.replace("Bengaluru and Gurugram", "Bangalore")
    df = df.replace("Delhi & Cambridge", "New Delhi")
    df = df.replace("Ahemadabad", "Ahmedabad")
    df = df.replace("Bangalore/ Bangkok", "Bangalore")
    df = df.replace("Kerala", "Trivandrum")
    df = df.replace("SFO / Bangalore", "Bangalore")
    df = df.replace("Pune/Seattle", "Pune")
    df = df.replace("Pune / Dubai", "Pune")
    df = df.replace("Bangalore / SFO", "Bangalore")
    df = df.replace("New Delhi / US", "New Delhi")
    df = df.replace("Mumbai / UK", "Mumbai")
    df = df.replace("Hyderabad/USA", "Hyderabad")
    df = df.replace("Bangalore / Palo Alto", "Bangalore")
    df = df.replace("Mumbai / NY", "Mumbai")
    df = df.replace("Noida / Singapore", "Noida")
    df = df.replace("Pune / US", "Pune")
    df = df.replace("Bangalore / San Mateo", "Bangalore")
    df = df.replace("Gurgaon / SFO", "Gurgaon")
    df = df.replace("Bangalore / USA", "Bangalore")
    df = df.replace("Mumbai / Global", "Mumbai")
    df = df.replace("Dallas / Hyderabad", "Hyderabad")
    
    df = df[df["Industry Vertical"] != 'Hyperlocal\\\\xc2\\\\xa0 Grocery Delivery Service']
    df = df[df["Industry Vertical"] != 'Mobile Growth Hacking\\\\nPlatform']
    df = df[df["Industry Vertical"] != 'OnDemand\\\\nMobile Handyman Services']
    df = df[df["Industry Vertical"] != 'Interactive\\\\xc2\\\\xa0 How-To Guides']
    df = df[df["Industry Vertical"] != 'Online Furnishing\\\\neCommerce']
    df = df[df["Industry Vertical"] != 'Online Home D\\\\xc3\\\\xa9cor']
    df = df[df["Industry Vertical"] != 'Healthcare\\\\nService provider']
    df = df[df["Industry Vertical"] != 'Online home d\\\\xc3\\\\xa9cor marketplac']
    df = df[df["Industry Vertical"] != 'Home Design & D\\\\xc3\\\\xa9cor solutions']
    df = df[df["Industry Vertical"] != 'App security\\\\xc2\\\\xa0 testing platform']
    df = df[df["Industry Vertical"] != 'Chain of Tea Caf\\\\xc3\\\\xa9\\\\xe2\\\\x80\\\\x99s']
    df = df[df["Industry Vertical"] != 'ECommerce Brands\\\\xe2\\\\x80\\\\x99 Full Service Agency']
    df = df[df["Industry Vertical"] != 'Luxury goods\\\\xc2\\\\xa0 Shopping Platform']
    df = df[df["Industry Vertical"] != 'Location based Nightlife recommendation\\\\xc2\\\\xa0 Platform']
    df = df[df["Industry Vertical"] != 'Women Ethnic Wear\\\\xc2\\\\xa0 Online Marketplace']
    df = df[df["Industry Vertical"] != 'Hyperlocal\\\\xc2\\\\xa0 Grocery Delivery Service']
    df = df[df["Industry Vertical"] != 'Online home d\\\\xc3\\\\xa9cor marketplace']
   
    df = df.replace("FinTech", "Finance")
    df = df.replace("E-commerce", "E-Commerce")
    df = df.replace("E-Tech", "Technology")
    df = df.replace("Online Travel Marketplace", "Travel")
    df = df.replace("Financial Markets Software", "Finance")
    df = df.replace("Hiring Analytics platform", "Analytics")
    df = df.replace("Startup Analytics platform", "Analytics")
    df = df.replace("Cloud Enterprise Software", "Cloud Computing")
    df = df.replace("Used Gadgets Buy / Refurbishing", "Resale")
    df = df.replace("Tele-Shopping / eCommerce", "E-Commerce")
    df = df.replace("Robotic Program learning", "Technology")
    df = df.replace("Interactive Educational Games", "Education")
    df = df.replace("Food Logistics & Delivery", "Logistics")
    df = df.replace("Restaurant Management Platform", "Technology")
    df = df.replace("Online Insurance Aggregator", "Insurance")
    df = df.replace("Auto Rickshaw based Logistics", "Logistics")
    df = df.replace("usiness expense management", "Finance")
    df = df.replace("Last Minute Travel Deals mobile marketplace", "Travel")
    df = df.replace("Ethnic Product eCommerce", "E-Commerce")
    df = df.replace("Online Certification Courses", "Education")
    df = df.replace("Private Coaching Centers", "Education")
    df = df.replace("Fashion ECommerce", "E-Commerce")
    df = df.replace("Online Classifieds & Listings", "News")
    df = df.replace("Online / Mobile Customer Support", "Technology")

#E-commerce

    df = df.replace("Hyperlocal Mobile Services Marketplace", "E-Commerce")
    df = df.replace("Hyper-Local Online/Mobile Grocery", "E-Commerce")
    df = df.replace("Hyper-local Online Services", "E-Commerce")
    df = df.replace("Online Kitchen Furniture", "E-Commerce")
    df = df.replace("Online Grocer", "E-Commerce")
    df = df.replace("On-demand Service marketplace", "E-Commerce")
    df = df.replace("Hyperlocal Mobile Marketplace", "E-Commerce")
    df = df.replace("Online Job skills Showcase", "E-Commerce")
    df = df.replace("Online Fashion Aggregator", "E-Commerce")
    df = df.replace("Lifestyle Ecommerce Portal", "E-Commerce")
    df = df.replace("Mobile Laundry Cleaning Service", "E-Commerce")
    df = df.replace("Online Art Marketplace", "E-Commerce")
    df = df.replace("Hyperlocal services marketplace", "E-Commerce")
    df = df.replace("Online education marketplace", "E-Commerce")
    df = df.replace("Online Coupon & comparison platform", "E-Commerce")
    df = df.replace("Home Furnishing Solutions", "E-Commerce")
    df = df.replace("Fashion Ecommerce store", "E-Commerce")
    df = df.replace("Mobile Commerce Platform", "E-Commerce")
    df = df.replace("Private Label lingerie Ecommerce", "E-Commerce")
    df = df.replace("eCommerce platform", "E-Commerce")
    df = df.replace("Bespoke Merchandize Marketplace", "E-Commerce")
    df = df.replace("Hyperlocal Grocery App", "E-Commerce")
    df = df.replace("Used Vehicle Marketplace", "E-Commerce")
    df = df.replace("Online Jewelry Store", "E-Commerce")
    df = df.replace("Hyperlocal Deals Marketplace", "E-Commerce")
    df = df.replace("Fitness Marketplace", "E-Commerce")
    df = df.replace("Online Grocers", "E-Commerce")
    df = df.replace("Organic Food ecommerce", "E-Commerce")
    df = df.replace("Industrial Supplies B2B ecommerce", "E-Commerce")
    df = df.replace("Online comparison engine", "E-Commerce")
    df = df.replace("Celebrity Fashion Brand", "E-Commerce")
    df = df.replace("Coupon Aggregator Platform", "E-Commerce")
    df = df.replace("Used Car Marketplace", "E-Commerce")
    df = df.replace("Online Coffee Delivery platform", "E-Commerce")
    df = df.replace("Beauty & Lifestyle Mobile Marketplace", "E-Commerce")
    df = df.replace("On-Demand Beauty Service", "E-Commerce")
    df = df.replace("on-Demand Washing & Dry-Cleaning", "E-Commerce")
    df = df.replace("Professional Custom creators Marketplace", "E-Commerce")
    df = df.replace("On-Demand App based Professional service provider", "E-Commerce")
    df = df.replace("Online marketplace for Photographers", "E-Commerce")
    df = df.replace("Online Diagnostic Tests Marketplace", "E-Commerce")
    df = df.replace("Online Furniture Marketplace", "E-Commerce")
    df = df.replace("Mobile Commerce for Farmers", "E-Commerce")
    df = df.replace("Online & mobile Grocery store", "E-Commerce")
    df = df.replace("Subscription based Online Grocery platform", "E-Commerce")
    df = df.replace("Online printing marketplace", "E-Commerce")
    df = df.replace("Hyper-Local Ecommerce", "E-Commerce")
    df = df.replace("Loyalty Programs & Reward Points", "E-Commerce")
    df = df.replace("Mobile Services Marketplace", "E-Commerce")
    df = df.replace("Online Jewellery etailer", "E-Commerce")
    df = df.replace("Online Real Estate Marketplace", "E-Commerce")
    df = df.replace("Indian Ethnic Crafts Etailer", "E-Commerce")
    df = df.replace("Online Furniture Home Appliances Rental Platform", "E-Commerce")
    df = df.replace("Health and Beauty Services Marketplace", "E-Commerce")
    df = df.replace("Online and TV Shopping Marketplace", "E-Commerce")
    df = df.replace("character merchandize sales platform", "E-Commerce")
    df = df.replace("Ecommerce Delivery locker services", "E-Commerce")
    df = df.replace("Ecommerce Marketplace", "E-Commerce")
    df = df.replace("Fashion Discovery platform", "E-Commerce")
    df = df.replace("E-Commerce & M-Commerce platform", "E-Commerce")
    df = df.replace("Private Label Apparel sales", "E-Commerce")
    df = df.replace("coupons and cashback aggregator app", "E-Commerce")
    df = df.replace("Private label Fashion eTailer", "E-Commerce")
    df = df.replace("B2B Mobile Auction Marketplace", "E-Commerce")
    df = df.replace("Used Vehicles Marketplace", "E-Commerce")
    df = df.replace("Industrial Tools Marketplace", "E-Commerce")
    df = df.replace("Online Lingerie Marketplace", "E-Commerce")
    df = df.replace("Professionals & Project Search Marketplace", "E-Commerce")
    df = df.replace("Premium Apparel shopping portal", "E-Commerce")
    df = df.replace("Fashion jewelry and accessories e-tailer", "E-Commerce")
    df = df.replace("Beauty & Wellness Products e-tailer", "E-Commerce")
    df = df.replace("mobile-only tasks marketplace", "E-Commerce")
    df = df.replace("eCommerce Product Search Engine", "E-Commerce")
    df = df.replace("Marketplace App for Bangkok", "E-Commerce")
    df = df.replace("Beauty and Wellness Marketplace", "E-Commerce")        
    df = df.replace("Online Vehicle Spare Parts etailer", "E-Commerce")
    df = df.replace("Online Grocery platform", "E-Commerce")
    df = df.replace("B2B Merchandize platform", "E-Commerce")
    df = df.replace("B2B eCommerce Marketplace", "E-Commerce")
    df = df.replace("Mobile accessories online store", "E-Commerce")
    df = df.replace("Home services marketplace", "E-Commerce")
    df = df.replace("Modular Furnishings Marketplace", "E-Commerce")
    df = df.replace("Wedding Venues & Vendors Marketplace", "E-Commerce")
    df = df.replace("Peer-to-Peer Money Transfer & Recharge App", "E-Commerce")
    df = df.replace("Mobile Point of Sale solutions", "E-Commerce")
    df = df.replace("Online Branded Furniture etailer", "E-Commerce")
    df = df.replace("Custom Made furniture e-tailer", "E-Commerce")
    df = df.replace("Online Wedding Marketplace", "E-Commerce")
    df = df.replace("ecommerce", "E-Commerce")
    df = df.replace("eCommece", "E-Commerce")
    df = df.replace("ECommerce", "E-Commerce")
    df = df.replace("eCommerce", "E-Commerce")
    df = df.replace("B2B Platform", "E-Commerce")
    df = df.replace("Ecommerce", "E-Commerce")
    df = df.replace("SaaS Ecommerce", "E-Commerce")
    df = df.replace("Online Marketplace", "E-Commerce")
    df = df.replace("Consumer Goods", "E-Commerce")
    df = df.replace("B2B", "E-Commerce")
    df = df.replace("E-Commerce", "E-Commerce")

    #Tech

    df = df.replace("Mobile App Development", "Technology")
    df = df.replace("Device Repair Svcs", "Technology")
    df = df.replace("Location Based App", "Technology")
    df = df.replace("Health Mobile App", "Technology")
    df = df.replace("Online Security Platform", "Technology")
    df = df.replace("Online Product Comparison", "Technology")
    df = df.replace("Workforce Management Software", "Technology")
    df = df.replace("Wealth Management Platform", "Technology")
    df = df.replace("Flat rental Mobile App'", "Technology")
    df = df.replace("Marketing / Advertising Automation platform", "Technology")
    df = df.replace("3D Printer Manufacturer'", "Technology")
    df = df.replace("Mobile Compression Software", "Technology")
    df = df.replace("Hyperlocal Shopping App", "Technology")
    df = df.replace("Probiotic Technology Products Manufacturer", "Technology")
    df = df.replace("Spa & Salon Management Software", "Technology")
    df = df.replace("Real Estate Broker network App", "Technology")
    df = df.replace("Tech Recruitment platform", "Technology")
    df = df.replace("Healthcare Mobile App", "Technology")
    df = df.replace("Online Food-Tech Platform", "Technology")
    df = df.replace("Custom Merchandize platform", "Technology")
    df = df.replace("IT infrastructure & Data Center services", "Technology")
    df = df.replace("Hyperlocal Electronics repair Service", "Technology")
    df = df.replace("Online Food Community Platform", "Technology")
    df = df.replace("Cross-channel CRM platform", "Technology")
    df = df.replace("Professional Service Appointment booking service", "Technology")
    df = df.replace("Corporate Wellness App", "Technology")
    df = df.replace("Car Aggregator & Retail Mobile App", "Technology")
    df = df.replace("Smartwatch Maker", "Technology")
    df = df.replace("Sales & Productivity Software", "Technology")
    df = df.replace("On Demand Laundry Services App", "Technology")
    df = df.replace("Hyper-local Grocery Delivery platform", "Technology")
    df = df.replace("Tech Platform for property brokers'", "Technology")
    df = df.replace("Digital Signal processing platform", "Technology")
    df = df.replace("Employee OnBoarding & Orientation platform", "Technology")
    df = df.replace("Digital & Physical Publishing platform", "Technology")
    df = df.replace("Cross-device retargeting platform", "Technology")
    df = df.replace("Online Interior Designing platform", "Technology")
    df = df.replace("virtual reality 3d simulation and stereoscopic products", "Technology")
    df = df.replace("Internet of Things platform", "Technology")
    df = df.replace("Wedding Planning Platform", "Technology")
    df = df.replace("Mobile App testing platform", "Technology")
    df = df.replace("pre-used apparel shopping mobile app", "Technology")
    df = df.replace("Gym & Fitness Studios Subscription platform", "Technology")
    df = df.replace("Job Search Platform", "Technology")
    df = df.replace("Personalized Styling platform", "Technology")
    df = df.replace("Document Digitization platform", "Technology")
    df = df.replace("Public Commute helper App", "Technology")
    df = df.replace("Hotel Aggregator & booking platform", "Technology")
    df = df.replace("Personal Diagnostic Mobile App", "Technology")
    df = df.replace("residential rental management platform", "Technology")
    df = df.replace("Personalized Wish List creator app", "Technology")
    df = df.replace("Mobile Only Shopping Assistant", "Technology")
    df = df.replace("Developer Portfolio Showcase platform", "Technology")
    df = df.replace("Rental Accommodation Search platform", "Technology")
    df = df.replace("Gesture based Mobile Development", "Technology")
    df = df.replace("Product discovery & recommendation platform", "Technology")
    df = df.replace("Online Products Discovery Platform", "Technology")
    df = df.replace("Virtual Reality Headset creator", "Technology")
    df = df.replace("Ecommerce Discount & Cashback coupons platform", "Technology")
    df = df.replace("Event Ticketing platform", "Technology")
    df = df.replace("New Curation Mobile App", "Technology")
    df = df.replace("Mobile Car Servicing appointment app", "Technology")
    df = df.replace("Grocery Delivery platform", "Technology")
    df = df.replace("Photographer Online search & booking platform", "Technology")
    df = df.replace("Mobile Game development & Design platform", "Technology")
    df = df.replace("Mobile Fitness App", "Technology")
    df = df.replace("Artificial Intelligence platform", "Technology")
    df = df.replace("Electric Bike Manufacturers", "Technology")
    df = df.replace("visual search and discovery platform", "Technology")
    df = df.replace("Picture creation & Social mobile app", "Technology")
    df = df.replace("Smart Safety Wearable Devices", "Technology")
    df = df.replace("Car Maintenance & Management mobile app", "Technology")
    df = df.replace("On Demand Mobile app developer", "Technology")
    df = df.replace("App based Bus Pooling Services", "Technology")
    df = df.replace("Transportation & Logistics Platform", "Technology")
    df = df.replace("Consumer Portal", "Technology")
    df = df.replace("Consumer internet", "Technology")
    df = df.replace("Clean-tech", "Technology")
    df = df.replace("Consumer Internet", "Technology")
    df = df.replace("Logistics Tech", "Technology")
    df = df.replace("Food-Tech", "Technology")
    df = df.replace("Services Platform", "Technology")
    df = df.replace("Deep-Tech", "Technology")
    df = df.replace("Tech", "Technology")
    df = df.replace("Consumer Technology", "Technology")
    df = df.replace("Technology", "Technology")

    #Finance

    df = df.replace("Digital / Mobile Wallet", "Finance")
    df = df.replace("Price Comparison", "Finance")
    df = df.replace("Real Estate Advisory", "Finance")
    df = df.replace("Fund Raising Platform'", "Finance")
    df = df.replace("Credit Management Services", "Finance")
    df = df.replace("Micro Finance Platform", "Finance")
    df = df.replace("Startup funding platform", "Finance")
    df = df.replace("Financial Services Platform", "Finance")
    df = df.replace("Peer to Peer Lending platform", "Finance")
    df = df.replace("Payment Solutions platform", "Finance")
    df = df.replace("F&B sector Mobile Payment platform", "Finance")
    df = df.replace("Crowd Funding Platform", "Finance")
    df = df.replace("Online Finance lending platform", "Finance")
    df = df.replace("Online Financial Services", "Finance")
    df = df.replace("Financial Inclusion platform", "Finance")
    df = df.replace("Mutual Fund Investing platform", "Finance")
    df = df.replace("Credit Card Fraud protection solutions'", "Finance")
    df = df.replace("mobile payment software platform'", "Finance")
    df = df.replace("Mobile App based Loan disbursement platform", "Finance")
    df = df.replace("Crowd funding platform'", "Finance")
    df = df.replace("fund raising platform for startups", "Finance")
    df = df.replace("Financial Services Portal", "Finance")
    df = df.replace("Real-Time stock data platform", "Finance")
    df = df.replace("Small Business Financing (NBFC)", "Finance")
    df = df.replace("FinTech Startup Incubation platform", "Finance")
    df = df.replace("Asset Financing platform", "Finance")
    df = df.replace("Online Payment Gateway", "Finance")
    df = df.replace("Payments Solution platform", "Finance")
    df = df.replace("End-to-End Lending platform", "Finance")
    df = df.replace("Online Consumer Lending platform", "Finance")
    df = df.replace("Mobile Payments App", "Finance")
    df = df.replace("Online Loans Marketplace", "Finance")
    df = df.replace("Alternate Mobile Monetization platform", "Finance")
    df = df.replace("Mobile Wallet", "Finance")
    df = df.replace("Nonbanking finance company", "Finance")
    df = df.replace("Fiinance", "Finance")
    df = df.replace("Fin-Tech", "Finance")
    df = df.replace("Financial Tech", "Finance")
    df = df.replace("Investment", "Finance")
    df = df.replace("NBFC", "Finance")
    df = df.replace("Fintech", "Finance")
    df = df.replace("Accounting", "Finance")
    df = df.replace("Finance", "Finance")

    #Analytics

    df = df.replace("Customer Engagement Platform", "Analytics")
    df = df.replace("Banking Analytics Platform", "Analytics")
    df = df.replace("App Analytics platform", "Analytics")
    df = df.replace("Data Driven recruitment recommendation", "Analytics")
    df = df.replace("IT / Customer Engagement Consulting", "Analytics")
    df = df.replace("Video Intelligence Platform", "Analytics")
    df = df.replace("Data Center Software platform", "Analytics")
    df = df.replace("Real Estate Intelligence Platform", "Analytics")
    df = df.replace("Big Data & Analytics Services", "Analytics")
    df = df.replace("Business intelligence & Analytics", "Analytics")
    df = df.replace("Restaurant customer engagement platform", "Analytics")
    df = df.replace("Big Data & Analytics platform", "Analytics")
    df = df.replace("Real Estate Rating & Analysis", "Analytics")
    df = df.replace("CRM / Analytics platform", "Analytics")
    df = df.replace("Food Customer analytics platform", "Analytics")
    df = df.replace("Data Analytics Platform", "Analytics")
    df = df.replace("Business and IT consulting", "Analytics")
    df = df.replace("User Engagment & Analytics platform", "Analytics")
    df = df.replace("Big Data Management Platform", "Analytics")
    df = df.replace("Data Driven Publishing platform", "Analytics")
    df = df.replace("Numerical Computing & Data Science Platform", "Analytics")
    df = df.replace("Online RTI application services", "Analytics")
    df = df.replace("Digital Analytics Platform", "Analytics")



    # Cloud Computing
    df = df.replace("API Workflow platform", "Cloud Computing")
    df = df.replace("Cloud Data Integration Platform", "Cloud Computing")
    df = df.replace("Language Localization Cloud platform", "Cloud Computing")
    df = df.replace("Deep Learning Cloud Algorithms", "Cloud Computing")
    df = df.replace("Mobile based PoS solution", "Cloud Computing")
    df = df.replace("Cloud software solutions", "Cloud Computing")
    df = df.replace("Cloud Based Collaboration platform", "Cloud Computing")
    df = df.replace("Test Automation SAAS platform", "Cloud Computing")
    df = df.replace("Internet Network Infrastructure Services", "Cloud Computing")
    df = df.replace("SaaS", "Cloud Computing")



    #Communication
    df = df.replace("On-Demand Business messaging", "Communication")
    df = df.replace("B2C Messaging App", "Communication")
    df = df.replace("Business Messaging App", "Communication")
    df = df.replace("Mobile Chat based concierge service", "Communication")
    df = df.replace("Social Network for Artists", "Communication")
    df = df.replace("Healthy Food Online Community", "Communication")
    df = df.replace("Picture based Social App'", "Communication")
    df = df.replace("mobile social network", "Communication")
    df = df.replace("conversational commerce mobile app", "Communication")
    df = df.replace("Social platform for traders and investors", "Communication")
    df = df.replace("Mobile Advertising platform", "Communication")
    df = df.replace("Online Student & Campus Social Networking platform", "Communication")
    df = df.replace("Mobile Messaging Assistant App", "Communication")


    #Med

    df = df.replace("Online Pharmacy & Drug DB", "Healthcare")
    df = df.replace("Online Medical Diagnostic", "Healthcare")
    df = df.replace("Dental Clinic chain", "Healthcare")
    df = df.replace("Global Healthcare products", "Healthcare")
    df = df.replace("Preventive Healthcare Services", "Healthcare")
    df = df.replace("Medical Tech Instruments", "Healthcare")
    df = df.replace("Clinical Genomics Provider", "Healthcare")
    df = df.replace("Health-Tech platform", "Healthcare")
    df = df.replace("Healthcare Services Discovery platform", "Healthcare")
    df = df.replace("Hyperlocal healthcare product Delivery Service provider", "Healthcare")
    df = df.replace("Doctor Appointment booking app", "Healthcare")
    df = df.replace("Home Medical Care Services", "Healthcare")
    df = df.replace("Diagnostic Labs aggregator platform", "Healthcare")
    df = df.replace("Online Health & Wellness platform'", "Healthcare")
    df = df.replace("Professional Health Services Platform", "Healthcare")
    df = df.replace("Online Pharmacy", "Healthcare")
    df = df.replace("Healthcare IT Solutions & services", "Healthcare")
    df = df.replace("on-demand healthcare marketplace", "Healthcare")
    df = df.replace("Online Homeopathy Clinic", "Healthcare")
    df = df.replace("Exclusive Platform for Doctors & Healthcare professionals", "Healthcare")
    df = df.replace("Medical Consultation & Doctor appointment booking platform", "Healthcare")
    df = df.replace("Digital Healthcare", "Healthcare")
    df = df.replace("healthcare", "Healthcare")
    df = df.replace("Health Care", "Healthcare")
    df = df.replace("Healthcare", "Healthcare")
    df = df.replace("Health and Wellness", "Healthcare")
    df = df.replace("Health and wellness", "Healthcare")


    #Waste
    df = df.replace("Material Collection & Recycling", "Waste Management")
    df = df.replace("Waste Management Solutions", "Waste Management")
    df = df.replace("Waste Management Service", "Waste Management")


    #Logistics
    df = df.replace("Last Mile Logistics", "Logistics")
    df = df.replace("Logistics Intelligence", "Logistics")
    df = df.replace("Trucking Logistic Operations", "Logistics")
    df = df.replace("Ecommerce Logistics", "Logistics")
    df = df.replace("Freight logistics platform", "Logistics")
    df = df.replace("Intra-City Logistics service", "Logistics")
    df = df.replace("Logistics Solution Provider", "Logistics")
    df = df.replace("Innovative Water Solutions", "Logistics")
    df = df.replace("Hyper local logistics platform", "Logistics")
    df = df.replace("Tech enabled logistics platform", "Logistics")
    df = df.replace("on-demand delivery service", "Logistics")
    df = df.replace("Logistics service platform", "Logistics")
    df = df.replace("On-Demand Delivery Logistics", "Logistics")
    df = df.replace("ECommerce Logistics provider", "Logistics")
    df = df.replace("Hyperlocal Grocery Delivery", "Logistics")
    df = df.replace("Food Delivery Platform", "Logistics")
    df = df.replace("End-to-end Logistics platform", "Logistics")
    df = df.replace("Online Food ordering & delivery", "Logistics")
    df = df.replace("Hyperlocal Delivery Services", "Logistics")
    df = df.replace("Autorickshaw Aggregator & Booking platform", "Logistics")
    df = df.replace("Online Logistics Platform", "Logistics")
    df = df.replace("Last Mile Delivery Service", "Logistics")
    df = df.replace("Logistics Tech Platform", "Logistics")
    df = df.replace("Delivery & Logistics Service provider", "Logistics")
    df = df.replace("QSR & Online delivery portal", "Logistics")
    df = df.replace("Logistics Service Provider Marketplace", "Logistics")
    df = df.replace("Logistics Services Provider", "Logistics")
    df = df.replace("End to End reverse logistics Solution platform", "Logistics")
    df = df.replace("Supply Chain & Logistics Solutions", "Logistics")
    df = df.replace("Logistics", "Logistics")
    df = df.replace("", "Logistics")

    #Entertainment
    df = df.replace("Video Streaming", "Entertainement")
    df = df.replace("Web Content Publishing", "Entertainement")
    df = df.replace("Parents focused Web Content", "Entertainement")
    df = df.replace("Online Fashion Video Portal", "Entertainement")
    df = df.replace("Music Streaming App", "Entertainement")
    df = df.replace("Visual Blogging platform", "Entertainement")
    df = df.replace("Viral Content web Platform", "Entertainement")
    df = df.replace("Nightlife Discovery Mobile App", "Entertainement")
    df = df.replace("Online Movie Review Platform", "Entertainment")
    df = df.replace("Online content platform for women", "Entertainment")
    df = df.replace("Virtual Health consultation app", "Entertainment")
    df = df.replace("Entertainment", "Entertainment")



    #Insurance
    df = df.replace("Online Policy Aggregator", "Insurance")
    df = df.replace("Online Insurance Distribution Platform", "Insurance")
    df = df.replace("Auto Insurance Online platform", "Insurance")


    #Travel
    df = df.replace("Online Hotel Booking", "Travel")
    df = df.replace("Cab Aggregator", "Transportation")
    df = df.replace("Travel Entertainment", "Travel")
    df = df.replace("Electric Scooter Manufacturer", "Transportation")
    df = df.replace("Self-driven Car rental", "Transportation")
    df = df.replace("Affordable Hotel Booking Online", "Travel")
    df = df.replace("Online Budget Hotel Booking Service", "Travel")
    df = df.replace("Auto Rickshaw Based Services", "Transportation")
    df = df.replace("Online Car Rental Affiliates", "Transportation")
    df = df.replace("Used Bikes Marketplace", "Transportation")
    df = df.replace("Travel information portal", "Travel")
    df = df.replace("Budget Hotel Accommodation", "Travel")
    df = df.replace("Bike Rental Platform", "Transportation")
    df = df.replace("Self-driven vehicle rental", "Transportation")
    df = df.replace("Taxi Rental platform", "Transportation")
    df = df.replace("Two-Wheeler Taxi Service", "Transportation")
    df = df.replace("Self Driven Rental Car Platform", "Transportation")
    df = df.replace("hotel booking app", "Travel")
    df = df.replace("Online budget hotel chain", "Travel")
    df = df.replace("Budget Hotel accommodation brand", "Travel")
    df = df.replace("Budget Accommodation Platform'", "Travel")
    df = df.replace("Cab Booking app platform", "Transportation")
    df = df.replace("Branded Budget Hotel Marketplace", "Travel")
    df = df.replace("Cab rental Mobile app", "Transportation")
    df = df.replace("Cloud-based Hotel Booking Platform", "Travel")
    df = df.replace("Ridesharing Mobile app", "Transportation")
    df = df.replace("Travel Destination Discovery platform", "Travel")
    df = df.replace("Ride Sharing platform", "Transportation")
    df = df.replace("Home Stay & room rentals platform", "Travel")
    df = df.replace("Budget Hotels Aggregator", "Travel")
    df = df.replace("Bus Aggregation and rental mobile app", "Transportation")
    df = df.replace("Cab search Comparison & Booking platform", "Transportation")
    df = df.replace("Cab Sharing service Mobile app", "Transportation")
    df = df.replace("Last Minute Hotel Booking App", "Travel")
    df = df.replace("Travel Tech", "Travel")
    df = df.replace("Last Mile Transportation", "Transportation")
    df = df.replace("Transport", "Transportation")



    #energy
    df = df.replace("Off-grid Solar Power", "Energy")
    df = df.replace("Renewable energy solutions", "Energy")
    df = df.replace("Solar Power Solutions company", "Energy")
    df = df.replace("Energy", "Energy")



    #Education
    df = df.replace("Online Ed-Tech Platform", "Education")
    df = df.replace("Online Education Platform", "Education")
    df = df.replace("Career Development", "Education")
    df = df.replace("Affordable Education", "Education")
    df = df.replace("Online Learning Platform", "Education")
    df = df.replace("Hasbro Toy Manufacturer", "Education")
    df = df.replace("Educational Board Games", "Education")
    df = df.replace("Language Learning App", "Education")
    df = df.replace("Exam Preparation Platform", "Education")
    df = df.replace("Career Community for Women", "Education")
    df = df.replace("Kids Tool kit for Innovation platform", "Education")
    df = df.replace("Mobile Learning Solutions", "Education")
    df = df.replace("Education Content Provider", "Education")
    df = df.replace("Multilingual Test Preparation Platform", "Education")
    df = df.replace("Government Test Preparation platform", "Education")
    df = df.replace("Study Material Marketplace", "Education")
    df = df.replace("Competitive exam learning platform", "Education")
    df = df.replace("Virtual Reality activity based learning platform", "Education")
    df = df.replace("E-Learning Service Provider", "Education")
    df = df.replace("Skill Training Startup", "Education")
    df = df.replace("Online Counselling and psychological support platform", "Education")
    df = df.replace("Digital Intelligent learning platform", "Education")
    df = df.replace("Sports Education Platform", "Education")
    df = df.replace("Data Science & UX design Learning platform", "Education")
    df = df.replace("Online School for Analytics learning", "Education")
    df = df.replace("Online Education Information platform", "Education")
    df = df.replace("Ed-tech", "Education")
    df = df.replace("Ed-Tech", "Education")
    df = df.replace("Online Education", "Education")
    df = df.replace("Edtech", "Education")
    df = df.replace("EdTech", "Education")
    df = df.replace("Education", "Education")




    #News
    df = df.replace("Online Classifieds", "News")
    df = df.replace("Online City & Lifestyle Guide", "News")
    df = df.replace("Online & Mobile classified listings", "News")
    df = df.replace("Community Driven News/Views Platform", "News")


# Construction
    df = df.replace("Architectural Design & Consulting", "Construction")
    df = df.replace("Hyperlocal Handyman Services", "Construction")
    df = df.replace("Luxury Rental Homes", "Construction")
    df = df.replace("Physical Storage warehouses", "Construction")
    df = df.replace("Budget Accommodation aggregator", "Construction")
    df = df.replace("Custom Furniture Marketplace", "Construction")
    df = df.replace("Hyperlocal Maintenance Repair & Cleaning services", "Construction")
    df = df.replace("engineering services company'", "Construction")
    df = df.replace("Automated Storage & Warehousing Solution", "Construction")
    df = df.replace("Hyperlocal Handyman services", "Construction")
    df = df.replace("Real Estate Broker Platform App", "Construction")
    df = df.replace("Structural & Civil Engg Service Automation", "Construction")



#Marketing
    df = df.replace("Video Advertisement Platform", "Marketing")
    df = df.replace("Digital Marketing Services", "Marketing")
    df = df.replace("Ecommerce Marketing Software Platform", "Marketing")
    df = df.replace("Mobile Marketing Automation Platform", "Marketing")
    df = df.replace("proximity marketing & Mobile Advertising platform", "Marketing")
    df = df.replace("Advertising & Marketing Community Networking platform", "Marketing")
    df = df.replace("Enterprise Marketing Automation platform", "Marketing")
    df = df.replace("Advertising Marketing", "Marketing")
    df = df.replace("B2B Marketing", "Marketing")



    #Food
    df = df.replace("Restaurant Reviews", "Food and Beverage")
    df = df.replace("Premium Beverages", "Food and Beverage")
    df = df.replace("Online Table Reservation", "Food and Beverage")
    df = df.replace("Offline Tea Chain", "Food and Beverage")
    df = df.replace("Online Food Delivery", "Food and Beverage")
    df = df.replace("Online Food Ordering", "Food and Beverage")
    df = df.replace("Healthy Food Manufacturer", "Food and Beverage")
    df = df.replace("Chinese food delivery", "Food and Beverage")
    df = df.replace("Hyperlocal food & grocery store", "Food and Beverage")
    df = df.replace("Fine Dining Restaurant Chain", "Food and Beverage")
    df = df.replace("Ethnic Beverages manufacturer", "Food and Beverage")
    df = df.replace("QSR Restaurant Chain", "Food and Beverage")
    df = df.replace("Restaurant Reservation Platform", "Food and Beverage")
    df = df.replace("Quick Service Restaurant Chain", "Food and Beverage")
    df = df.replace("Fast food Chain Franchisee", "Food and Beverage")
    df = df.replace("Restaurant Discount app", "Food and Beverage")
    df = df.replace("Online Meat Ordering platform", "Food and Beverage")
    df = df.replace("Food Subscription platform", "Food and Beverage")
    df = df.replace("Dairy Based Product Manufacturer", "Food and Beverage")
    df = df.replace("Restaurant Ratings & Reviews platform", "Food and Beverage")
    df = df.replace("Food Discovery & Delivery Mobile app", "Food and Beverage")
    df = df.replace("Online food ordering & Delivery service", "Food and Beverage")
    df = df.replace("Home Made Food Marketplace", "Food and Beverage")
    df = df.replace("Micro-Brewery", "Food and Beverage")
    df = df.replace("Raw Meat & Ready to eat food etailer", "Food and Beverage")
    df = df.replace("Food Ordering & Delivery App", "Food and Beverage")
    df = df.replace("Home Cooked Food marketplace & Delivery", "Food and Beverage")
    df = df.replace("Branded Food products online sales", "Food and Beverage")
    df = df.replace("Ready to cook packaged Foods", "Food and Beverage")
    df = df.replace("Premium dining Lounges & restaurants", "Food and Beverage")
    df = df.replace("Quick Service Restaurant & Online Delivery", "Food and Beverage")
    df = df.replace("Online Food Ordering Marketplace", "Food and Beverage")
    df = df.replace("Online Food Ordering & Delivery platform", "Food and Beverage")
    df = df.replace("Home Cooked Food Order & Delivery platform", "Food and Beverage")
    df = df.replace("QSR Chain", "Food and Beverage")
    df = df.replace("Online Food ordering & Delivery platform", "Food and Beverage")
    df = df.replace("Food & Beverage", "Food and Beverage")
    df = df.replace("Food and Beverages", "Food and Beverage")
    df = df.replace("Food & Beverages", "Food and Beverage")
    df = df.replace("Food", "Food and Beverage")
    df = df.replace("Food and Beverage", "Food and Beverage")
    df = df.replace("B2B-focused foodtech startup", "Food and Beverage")
    df = df.replace("", "Food and Beverage")


    df = df.replace("Non Profit Organization to alleviate poverty", "Misc")
    df = df.replace("Sports Management & Physical Education Business", "Misc")
    df = df.replace("Job Board", "Misc")
    df = df.replace("Fitness Tracking Management Solutions", "Misc")
    df = df.replace("Designer fashion Jewellery Marketplace", "Misc")
    df = df.replace("Cricket Management Mobile Game", "Misc")
    df = df.replace("On-demand Maids Service Provider", "Misc")
    df = df.replace("Domestic Help Aggregation platform", "Misc")
    df = df.replace("International Hiring Platform", "Misc")
    df = df.replace("Online Freight Services Aggregator", "Misc")
    df = df.replace("Reality", "Misc")
    df = df.replace("FMCG", "Misc")
    df = df.replace("Others", "Misc")
    df = df.replace("Lifestyle", "Misc")
    df = df.replace("Inspiration", "Misc")
    df = df.replace("Agriculture", "Misc")
    df = df.replace("Publishing", "Misc")
    df = df.replace("Media", "Misc")
    df = df.replace("IT", "Misc")
    df = df.replace("Real Estate", "Misc")
    df = df.replace("Nanotechnology", "Misc")
    df = df.replace("Services", "Misc")
    df = df.replace("Digital Media", "Misc")
    df = df.replace("Luxury Label", "Misc")
    df = df.replace("Artificial Intelligence", "Misc")
    df = df.replace("Compliance", "Misc")
    df = df.replace("Retail", "Misc")
    df = df.replace("Information Technology", "Misc")
    df = df.replace("Customer Service", "Misc")
    df = df.replace("Video Games", "Misc")
    df = df.replace("Gaming", "Misc")
    df = df.replace("Video", "Misc")
    df = df.replace("Aerospace", "Misc")
    df = df.replace("Hospitality", "Misc")
    df = df.replace("Fashion and Apparel", "Misc")
    
    df = df.replace("Fashion", "Misc")
    df = df.replace("Saas", "Cloud Computing")

    df = df.replace("Automobile", "Misc")
    df = df.replace("Agtech", "Misc")
    df = df.replace("Social Media", "Communication")
    df = df.replace("Entertainement", "Entertainment")
    df = df.replace("Hyperlocal Logistics Service", "Logistics")
    df = df.replace("Online Health & Wellness platform", "Healthcare")
    df = df.replace("Budget Accommodation Platform", "Travel")
    df = df.replace("Tech Platform for property brokers", "Technology")
    df = df.replace("Crowd funding platform", "Finance")
    df = df.replace("mobile payment software platform", "Finance")
    df = df.replace("engineering services company", "Construction")
    df = df.replace("Credit Card Fraud protection solutions", "Finance")
    df = df.replace("Picture based Social App", "Communication")
    df = df.replace("3D Printer Manufacturer", "Technology")
    df = df.replace("Flat rental Mobile App", "Technology")
    df = df.replace("Fund Raising Platform", "Finance")
    df = df.replace("Grey collar Job Board", "Technology")
    
    df.replace("Seed/ Angel Funding", "Seed / Angel Funding")
    df.replace("Private", "Private Equity")
    df = df.replace("PrivateEquity", "Private Equity")
    df = df.replace("Term Loan", "Loan")
    df = df.replace("Structured Debt", "Debt Funding")
    df = df.replace("Angel / Seed Funding", "Seed & Angel Funding")
    df = df.replace("Private", "Private Equity")
    df = df.replace("Seed / Angle Funding", "Seed & Angel Funding")
    df = df.replace("Seed/Angel Funding", "Seed & Angel Funding")
    df = df.replace("Seed / Angel Funding", "Seed & Angel Funding")
    df = df.replace("Private Funding", "Private Equity")
    df = df.replace("Equity Based Funding", "Debt Funding")
    df = df.replace("Equity", "Private Equity")
    df = df.replace("Seed/ Angel Funding", "Seed & Angel Funding")
    df = df.replace("Inhouse Funding", "Retained Earnings Funding")
    df = df.replace("Debt and Preference capital", "Debt Funding")
    df = df.replace("pre-Series A", "Pre-series A")
    df = df.replace("Angel Round", "Angel Funding")
    df = df.replace("Angel", "Angel Funding")
    df = df.replace("Venture Round", "Venture Capital")
    df = df.replace("Corporate Round", "Corporate Funding")
    df = df.replace("Seed Funding Round", "Seed Funding")
    df = df.replace("Seed", "Seed Funding")
    df = df.replace("Seed Round", "Seed Funding")
    df = df.replace("Mezzanine", "Seed Funding")
    df = df.replace("Debt and Preference capital", "Debt Funding")
    df = df.replace("Private Equity Round", "Private Equity")
    
    df2 = (df
          )

    df2['Date'] = pd.to_datetime(df2['Date dd/mm/yyyy'], errors= 'coerce')
    
    df3 = df2.drop('Date dd/mm/yyyy', axis=1)



    return df3